
// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://bvnglrtwcrysosinnnem.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImJ2bmdscnR3Y3J5c29zaW5ubmVtIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDMyNTY4ODAsImV4cCI6MjA1ODgzMjg4MH0.pNvaM8npTJIjwj8Y2eoD29e79A2vG8IVuJ8y0CxlfLw";

// Environment variables for API endpoints
export const PARSE_CV_ENDPOINT = "https://europe-west9-hireable-places.cloudfunctions.net/cv_optimizer";
export const GENERATE_CV_ENDPOINT = ""; // To be populated later

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});
