// This file is automatically generated. Do not edit it directly.
import { createBrowserClient } from '@supabase/ssr'
import type { Database } from './types'

// Environment variables for API endpoints
export const PARSE_CV_ENDPOINT = "https://europe-west9-hireable-places.cloudfunctions.net/cv_optimizer"
export const GENERATE_CV_ENDPOINT = "" // To be populated later

// Create and export the Supabase client
export function createClient() {
  return createBrowserClient<Database>(
    process.env.NEXT_PUBLIC_SUPABASE_URL!,
    process.env.NEXT_PUBLIC_SUPABASE_ANON_KEY!
  )
}

// Export a default instance for backward compatibility
export const supabase = createClient()
